TodoService/config/routes.rb
TodoService::Application.routes.draw do
  resources :todos
  resources :users
  resources :sessions, only: [:create, :destroy]

  match '/signin', to: 'sessions#create'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'main#index'

end

TodoService/app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :content, :priority, :user_id

  belongs_to :user
end

TodoService/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password
  has_many :todos
  validates :name, presence: true
  validates :password, presence: true
end

TodoService/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

TodoService/app/controllers/main_controller.rb
class MainController < ApplicationController
	include SessionsHelper

	def index
		@current_user = current_user
	end
end

TodoService/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	require 'bcrypt'
	def create
		username = params[:name]
		pass = params[:password]

		@user = User.find_by_name(username)
		if !@user.nil? && BCrypt::Password.new(@user.password) == pass
			session[:current_user_id] = @user.id
			render :json => { :name => @user.name, :id => @user.id }
		else
			session[:current_user_id] = nil
			render :json => { error: "Invalid user/password combination" }
		end
	end

	def destroy
		session[:current_user_id] = nil;
		render :json => { :status => :success }
	end
end

TodoService/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  include SessionsHelper
  before_filter :signed_in_user

  def index
	  todos = current_user.todos
	  respond_to do |format|
		  format.html { render :partial => 'todo', :collection => todos }
		  format.json { render :json => todos }
	  end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])

	# make sure the current user owns this todo
	if @todo.user.id != current_user.id
		render :json => { :error => "You don't have access to this item." }
	else
		respond_to do |format|
		  format.html { render :partial => "todo", :locals => { :todo => @todo } }
		  format.json { render json: @todo }
		end
	end
  end

  # POST /todos
  # POST /todos.json
  def create
	params[:todo][:user_id] = current_user.id
    @todo = Todo.new(params[:todo])

    respond_to do |format|
      if @todo.save
        #format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render json: @todo, status: :created, location: @todo }
      else
        #format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])

	if @todo.user.id != current_user.id
		render :json => { :error => "You don't have access to this item." }
	end

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])

	if @todo.user.id != current_user.id
		render :json => { :error => "You don't have access to this item." }
	end

    @todo.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def signed_in_user
	  render :json => { :error => "Unauthorized" } if current_user.nil?
  end
end

TodoService/app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'bcrypt'
  # POST /users
  # POST /users.json
  def create
	params[:user][:password] = BCrypt::Password.create(params[:user][:password])
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

TodoService/app/helpers/application_helper.rb
module ApplicationHelper
end

TodoService/app/helpers/sessions_helper.rb
module SessionsHelper
	require 'bcrypt'

	def current_user=(user)
		@current_user = user
	end

	def current_user
		id = session[:current_user_id]
		@current_user ||= User.find_by_id(id)

		# check for user/pass params passed by API caller
		if @current_user.nil?
			username = params[:username]
			pass = params[:password]
			user = User.find_by_name(username)
			@current_user = user if user && BCrypt::Password.new(user.password) == pass
		end

		return @current_user
	end
end

TodoService/app/helpers/todos_helper.rb
module TodosHelper
end

TodoService/app/helpers/users_helper.rb
module UsersHelper
end

TodoService/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoService</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

TodoService/app/views/main/index.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/ui-lightness/jquery-ui.min.css">
<script type="text/javascript">
	// set up click handlers, sort todos by priority, other init
	$(function() {
		<% if @current_user.nil? %>
			uiLogout();
		<% else %>
			uiLogin("<%= @current_user.name %>");
			sortTodos("asc");
		<% end %>

		$("#add-item").click(function() { addItem(); });
		$("#submit-reg").click(function() { submitRegistration(); });
		$("#submit-login").click(function() { submitLogin(); });
		$("#open-reg").click(function() { $("#registration-form").dialog({ title: "Registration" }); });
		$("#open-login").click(function() { $("#login-form").dialog({ title: "Log in" }); });
		$("#logout").click(function() { doLogout(); });

		$("#sort-asc").click(function() { sortTodos("asc"); });
		$("#sort-desc").click(function() { sortTodos("desc"); });
	});

	function submitRegistration() {
		var name = $("#reg-username").val();
		var pass = $("#reg-password").val();
		var passRepeat = $("#reg-password-repeat").val();

		if (pass != passRepeat) {
			alert("Oops! The re-typed password doesn't match the original. Please re-enter your registration password and try again.");
			return;
		}

		url = "/users";
		data = { name: name, password: pass };
		ajaxPost(url, data,
			function(data) {
				alert("Registration successful!");
				$("#registration-form").dialog("close");
				// clear reg form fields
				$("#reg-username").val("");
				$("#reg-password").val("");
				$("#reg-password-repeat").val("");
			},
			function(err) {
				alert("There was a problem with your registration.");
			} );
	}

	function submitLogin() {
		var name = $("#login-username").val();
		var pass = $("#login-password").val();

		function processLogin(data) {
			if (data.error == undefined)
			{
				// clean up and close login form
				$("#login-form").dialog("close");
				$("#login-username").val("");
				$("#login-password").val("");

				// load todos
				$.get("/todos", function(data) { $("#todo-list").html(data); });
				sortTodos("asc");

				uiLogin(data.name);
			}
			else
				alert(data.error);
		}

		url = "/signin";
		data = { name: name, password: pass };
		ajaxPost(url, data, processLogin, null);
	}

	function uiLogout() {
		$("#logged-in-state").hide();
		$("#logged-out-state").show();
		$("#todo-list").html("");
		$("#todo-area-logged-in").hide();
		$("#todo-area-logged-out").show();
	}

	function uiLogin(username) {
		// set name on div w/ welcome message & logout button, show
		$("#logged-in-state .name").text(username);

		$("#logged-out-state").hide();
		$("#logged-in-state").show();
		$("#todo-area-logged-out").hide();
		$("#todo-area-logged-in").show();
	}


	function doLogout() {
		function processLogout(data) { uiLogout(); }
		ajaxDelete("/signout", {}, processLogout, function(err) { console.debug(err); });
	}

	function addItem() {
		var content = $("#add-item-content").val();
		var priority = $("#add-item-priority").val();

		createTodo(content, priority);

		// clear out contents of 'add item' form
		$("#add-item-content").val("");
		$("#add-item-priority").val("1");
	}

	function sortTodos(direction) {
		todos = $(".todo-item");

		function getTodoPriority(todo) { return $(todo).find(".priority").val(); }

		for (var i = 1; i <= 10; i++) {
			var filteredTodos = todos.filter(function() { return getTodoPriority(this) == i.toString(); });
			filteredTodos.each(function() {
					$(this).detach();
					if (direction != "desc")
						$("#todo-list").append(this);
					else
						$("#todo-list").prepend(this);
				});
		}
	}

	// creates a todo and adds it to the todo list
	function createTodo(content, priority) {
		var todoData = { content: content, priority: priority };

		// create new todo, add to todo list
		ajaxPost("/todos.json", todoData,
			function(data) {
			if (data.id != undefined)
				addTodoToUI(data.id);
			},
			function(err) { console.debug(err); });
	}

	// fetches a todo from the server and adds it to the todo list
	function addTodoToUI(id) {
		$.get("todos/" + id, function(data) { $("#todo-list").append(data); });
	}

	// deletes a todo and removes it from the todo list
	function deleteTodo(id) {
		url = "/todos/" + id;
		data = { id: id };
		ajaxDelete(url, data, null, null);
		item = getTodoEltWithId(id);
		item.remove();
	}

	function updateTodo(id) {
		item = getTodoEltWithId(id);
		content = $(item).find(".content").val();
		priority = $(item).find(".priority").val();
		console.log("Updating item #" + id + " with content '" + content + "' and priority of " + priority);

		var updateData = { content: content, priority: priority };
		var updateUrl = "/todos/" + id;
		ajaxPut(updateUrl, updateData, null,
				function(err) { alert("An error occurred while updating the todo."); } ); 
	}

	function getTodoEltWithId(id) {
		return $(".todo-item input.id").filter(function() { return $(this).val() === id.toString(); })
									   .parent();
	}

	function ajaxPost(url, jsonData, successFn, failureFn) {
		ajaxHelper("POST", url, jsonData, successFn, failureFn);
	}

	function ajaxDelete(url, jsonData, successFn, failureFn) {
		ajaxHelper("DELETE", url, jsonData, successFn, failureFn);
	}

	function ajaxPut(url, jsonData, successFn, failureFn) {
		ajaxHelper("PUT", url, jsonData, successFn, failureFn);
	}

	function ajaxHelper(method, url, jsonData, successFn, failureFn) {
		$.ajax({
			type: method,
			url: url,
			data: JSON.stringify(jsonData),
			contentType: "application/json; charset=utf-8",
			dataType: "json",
			success: successFn,
			failure: failureFn
		});
	}
</script>

<div id="dialogs" style="display: none;">
	<div id="registration-form">
		<label for="reg-username">Username:</label>
		<input type="text" id="reg-username" /><br/>
		<label for="reg-password">Password:</label>
		<input type="password" id="reg-password" /> <br/>
		<label for="reg-password-repeat">Re-type password:</label>
		<input type="password" id="reg-password-repeat" /><br/>
		<input type="button" value="Register" id="submit-reg" />
	</div>

	<div id="login-form">
		<label for="login-username">Username:</label>
		<input type="text" id="login-username" /><br/>
		<label for="login-password">Password:</label>
		<input type="password" id="login-password" /><br/>
		<input type="button" value="Log in" id="submit-login" />
	</div>
</div>

<div id="login-status">
	<div id="logged-out-state">
		<input type="button" value="Register" id="open-reg" />
		<input type="button" value="Log in" id="open-login" />
	</div>
	<div id="logged-in-state">
		<p>Welcome, <span class="name" style="font-weight: bold;"><%= @current_user.nil? ? "" : @current_user.name %></span>!
		<input type="button" value="Log out" id="logout" />
		</p>
	</div>
</div>

<hr/>

<h2>Todo list</h2>

<div id="todo-area-logged-out">
	Log in to view your todo list!
</div>
<div id="todo-area-logged-in">
<input type="button" value="Sort ascending" id="sort-asc" />
<input type="button" value="Sort descending" id="sort-desc" />
<!-- Todo list -->
<div id="todo-list">
	<% if !@current_user.nil? %>
		<%= render :partial => 'todos/todo', :collection => @current_user.todos %>
	<% end %>
</div>
<br />
<!-- Add todo item -->
<input type="text" size="40" id="add-item-content"/>
<select id="add-item-priority">
	<option value="1">1</option>
	<option value="2">2</option>
	<option value="3">3</option>
	<option value="4">4</option>
	<option value="5">5</option>
	<option value="6">6</option>
	<option value="7">7</option>
	<option value="8">8</option>
	<option value="9">9</option>
	<option value="10">10</option>
</select>
<input type="button" value="Add new todo item" id="add-item"/>
</div>

TodoService/app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TodoService/app/views/todos/_todo.html.erb
<div class="todo-item">
	<input type="hidden" value="<%= todo.id %>" class="id"/>
	<input type="text" size="40" value="<%= todo.content %>"/ class="content">
	<select class="priority">
	<% (1..10).each do |i| %>
		<option value="<%=i%>" <% if todo.priority == i %>selected<% end %>><%=i%></option>
	<% end %>
	</select>
	<input type="button" value="Save changes" onClick="updateTodo(<%= todo.id %>)"/>
	<input type="button" value="Delete" onClick="deleteTodo(<%= todo.id %>)"/>
</div>

TodoService/app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

TodoService/app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Priority</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.content %></td>
    <td><%= todo.priority %></td>
    <td><%= todo.user_id %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo', new_todo_path %>

TodoService/app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

TodoService/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @todo.content %>
</p>

<p>
  <b>Priority:</b>
  <%= @todo.priority %>
</p>

<p>
  <b>User:</b>
  <%= @todo.user_id %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

TodoService/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TodoService/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

TodoService/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

TodoService/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

TodoService/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>